const mongoose = require('mongoose'); const Dog = require('../models/Dog');
const invalidId = (id) => !mongoose.isValidObjectId(id);
const pagination = (query) => { const page = Math.max(parseInt(query.page, 10) || 1, 1); const limit = Math.min(Math.max(parseInt(query.limit, 10) || 10, 1), 100); return { page, limit, skip: (page - 1) * limit }; };
const paged = async (res, filter, query) => { const { page, limit, skip } = pagination(query); const [dogs, total] = await Promise.all([Dog.find(filter).sort({ createdAt: -1 }).skip(skip).limit(limit).populate('owner', 'username').populate('adoptedBy', 'username'), Dog.countDocuments(filter)]); return res.json({ dogs, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); };
exports.create = async (req, res, next) => { try { const { name, description } = req.body; if (!name || !description) return res.status(400).json({ message: 'Name and description are required.' }); const dog = await Dog.create({ name, description, owner: req.user.id }); return res.status(201).json({ dog }); } catch (error) { if (error.name === 'ValidationError') return res.status(400).json({ message: error.message }); return next(error); } };
exports.adopt = async (req, res, next) => { try { if (invalidId(req.params.id)) return res.status(400).json({ message: 'Invalid dog ID.' }); const { thankYouMessage } = req.body; if (!thankYouMessage) return res.status(400).json({ message: 'A thank-you message is required.' }); const dog = await Dog.findById(req.params.id); if (!dog) return res.status(404).json({ message: 'Dog not found.' }); if (dog.owner.equals(req.user.id)) return res.status(403).json({ message: 'You cannot adopt a dog you registered.' }); if (dog.adoptedBy) return res.status(409).json({ message: 'This dog has already been adopted.' }); dog.adoptedBy = req.user.id; dog.thankYouMessage = thankYouMessage; dog.adoptedAt = new Date(); await dog.save(); return res.json({ dog }); } catch (error) { return next(error); } };
exports.remove = async (req, res, next) => { try { if (invalidId(req.params.id)) return res.status(400).json({ message: 'Invalid dog ID.' }); const dog = await Dog.findById(req.params.id); if (!dog) return res.status(404).json({ message: 'Dog not found.' }); if (!dog.owner.equals(req.user.id)) return res.status(403).json({ message: 'Only the owner can remove this dog.' }); if (dog.adoptedBy) return res.status(409).json({ message: 'An adopted dog cannot be removed.' }); await dog.deleteOne(); return res.status(204).send(); } catch (error) { return next(error); } };
exports.listRegistered = async (req, res, next) => { try { const filter = { owner: req.user.id }; if (req.query.status === 'available') filter.adoptedBy = null; else if (req.query.status === 'adopted') filter.adoptedBy = { $ne: null }; else if (req.query.status) return res.status(400).json({ message: 'Status must be available or adopted.' }); return paged(res, filter, req.query); } catch (error) { return next(error); } };
exports.listAdopted = async (req, res, next) => { try { return paged(res, { adoptedBy: req.user.id }, req.query); } catch (error) { return next(error); } };
